### ISSUE TITLE
Suggestion for a presence sensor

### ISSUE THREAD

**Issue by pardeike** [mike-rankin/ESP32-S3_MLX90640_Thermal#1]
Hi, 
I was about to make my own when I stumbled over this project. It’s compact and that’s why I like it. I wonder if you would be interested in making a minimal version that only has the sensor and no large usb contact so I can package it with my own 5V transformer into a 3D case I can make my own. The purpose is to mount it at the ceiling and have it connected to main from the lamp (always on since I use Home Automation). I therefore would not need a screen. 

On the software side I got all the basics already working with an Atom S3 and the same thermal sensor also from M5Stack but I want to put such a presence sensor into every room and since I am a developer I could make a nice UX that allows to define zones that one can map to mqtt and thus Home Assistant. I would need a way to flash it though so maybe the usb has to at least exist before mounting it to the ceiling. 

/Andreas

**Comment by mike-rankin** [comment]
Not a problem Andreas,
I have a few off board usb options when space is tight. Please email me at 0miker0@gmail.com and I can attach the images.
